// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xloinhoycvrywpnxkuky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhsb2luaG95Y3ZyeXdwbnhrdWt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMDIxNjUsImV4cCI6MjA2MDU3ODE2NX0.2fQcC_UOfbhd-ZW_Y38d_nCudIx8E8cgTUxKvYUDsT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);